"""Authoritative bootstrap catalog for Mananze OS tools.

This module only defines and registers ToolDefinition contracts.
It does not execute tools, approve actions, or register providers.
"""

from .tool_registry import ToolDefinition, ToolRegistry


TOOLS: tuple[ToolDefinition, ...] = (
    ToolDefinition(
        tool_id="mananze:marketing:campaign_plan",
        version="1.0.0",
        description="Creates a structured marketing campaign plan.",
        capability_id="marketing",
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        required_permission_ids=("permission:marketing",),
        risk="low",
        estimated_cost=0.0,
        cost_currency="ZAR",
        timeout_seconds=30.0,
        max_attempts=1,
        execution_mode="internal",
        audit_required=True,
        requires_approval=False,
    ),
    ToolDefinition(
        tool_id="mananze:marketing:content_draft",
        version="1.0.0",
        description="Produces structured marketing content drafts.",
        capability_id="marketing",
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        required_permission_ids=("permission:marketing",),
        risk="low",
        estimated_cost=0.0,
        cost_currency="ZAR",
        timeout_seconds=30.0,
        max_attempts=1,
        execution_mode="internal",
        audit_required=True,
        requires_approval=False,
    ),
    ToolDefinition(
        tool_id="mananze:sales:lead_qualification",
        version="1.0.0",
        description="Evaluates and structures sales-lead qualification data.",
        capability_id="sales",
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        required_permission_ids=("permission:sales",),
        risk="medium",
        estimated_cost=0.0,
        cost_currency="ZAR",
        timeout_seconds=30.0,
        max_attempts=1,
        execution_mode="internal",
        audit_required=True,
        requires_approval=False,
    ),
    ToolDefinition(
        tool_id="mananze:sales:follow_up_plan",
        version="1.0.0",
        description="Creates a structured sales follow-up plan.",
        capability_id="sales",
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        required_permission_ids=("permission:sales",),
        risk="medium",
        estimated_cost=0.0,
        cost_currency="ZAR",
        timeout_seconds=30.0,
        max_attempts=1,
        execution_mode="internal",
        audit_required=True,
        requires_approval=False,
    ),
    ToolDefinition(
        tool_id="mananze:revenue:performance_report",
        version="1.0.0",
        description="Produces a structured revenue performance report.",
        capability_id="revenue",
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        required_permission_ids=("permission:revenue",),
        risk="medium",
        estimated_cost=0.0,
        cost_currency="ZAR",
        timeout_seconds=30.0,
        max_attempts=1,
        execution_mode="internal",
        audit_required=True,
        requires_approval=False,
    ),
    ToolDefinition(
        tool_id="mananze:reporting:business_report",
        version="1.0.0",
        description="Produces a structured business report from supplied evidence.",
        capability_id="reporting",
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        required_permission_ids=("permission:reporting",),
        risk="low",
        estimated_cost=0.0,
        cost_currency="ZAR",
        timeout_seconds=30.0,
        max_attempts=1,
        execution_mode="internal",
        audit_required=True,
        requires_approval=False,
    ),
    ToolDefinition(
        tool_id="mananze:customer_communications:message_draft",
        version="1.0.0",
        description="Creates a structured customer communication draft.",
        capability_id="customer_communications",
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        required_permission_ids=("permission:customer_communications",),
        risk="medium",
        estimated_cost=0.0,
        cost_currency="ZAR",
        timeout_seconds=30.0,
        max_attempts=1,
        execution_mode="internal",
        audit_required=True,
        requires_approval=False,
    ),
    ToolDefinition(
        tool_id="mananze:logistics:route_plan",
        version="1.0.0",
        description="Creates a structured logistics route plan.",
        capability_id="logistics",
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        required_permission_ids=("permission:logistics",),
        risk="medium",
        estimated_cost=0.0,
        cost_currency="ZAR",
        timeout_seconds=30.0,
        max_attempts=1,
        execution_mode="internal",
        audit_required=True,
        requires_approval=False,
    ),
    ToolDefinition(
        tool_id="mananze:fleet:fleet_status",
        version="1.0.0",
        description="Structures fleet status and monitoring information.",
        capability_id="fleet",
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        required_permission_ids=("permission:fleet",),
        risk="medium",
        estimated_cost=0.0,
        cost_currency="ZAR",
        timeout_seconds=30.0,
        max_attempts=1,
        execution_mode="internal",
        audit_required=True,
        requires_approval=False,
    ),
    ToolDefinition(
        tool_id="mananze:cost_analysis:cost_review",
        version="1.0.0",
        description="Reviews supplied operational cost information.",
        capability_id="cost_analysis",
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        required_permission_ids=("permission:cost_analysis",),
        risk="medium",
        estimated_cost=0.0,
        cost_currency="ZAR",
        timeout_seconds=30.0,
        max_attempts=1,
        execution_mode="internal",
        audit_required=True,
        requires_approval=False,
    ),
    ToolDefinition(
        tool_id="mananze:operations:workflow_plan",
        version="1.0.0",
        description="Creates a structured operational workflow plan.",
        capability_id="operations",
        input_schema={"type": "object"},
        output_schema={"type": "object"},
        required_permission_ids=("permission:operations",),
        risk="medium",
        estimated_cost=0.0,
        cost_currency="ZAR",
        timeout_seconds=30.0,
        max_attempts=1,
        execution_mode="internal",
        audit_required=True,
        requires_approval=False,
    ),
)


def register_default_tools(registry: ToolRegistry | None = None) -> ToolRegistry:
    """Register the authoritative Mananze OS tool contracts."""
    target = registry or ToolRegistry()

    for tool in TOOLS:
        target.register(tool)

    return target


def default_tool_registry() -> ToolRegistry:
    """Return a fresh registry containing all default OS tools."""
    return register_default_tools()


__all__ = [
    "TOOLS",
    "default_tool_registry",
    "register_default_tools",
]
